# dataset info
dataset_name: "afhqv2"

# solver info
sampler_stu: ipndm
afs: True
schedule_type: logsnr
schedule_rho: 7


# training info

loss_type: inception
loss_weight: constant
mode: lambda
predict_x0: True
noise_schedule: VE
guidance_type: None
bound_tn: 0.05
bound_tn2: 0.5
bound_epscaling: 0.05
window_rate: 0.05
use_ema: True
learn_bound: False
batch: 4
sampling_batch: 256
run_valid: False


total_kimg: 10
valid_num: 1000
train_num: 10000
noise_handler: uncond # fullsvd values None golden
noisenethidden_dim: 128
noisenet_topk: 16
alter_training: False
num_workers: 4

lr_param: 0.05
lr_net: 0.05
frequency: 10


# path info
model_path: ../../pretrained/edm/edm-afhqv2-64x64-uncond-vp.pkl
ref_path: ../../pretrained/edm/fid_refs/afhqv2-64x64.npz
datadir: ../logs/indis/data/afhqv2logsnr30
